/**
 * Route tree generation placeholder
 * This file will be auto-generated by TanStack Start
 */

import { Route as rootRoute } from './routes/__root';
import { Route as indexRoute } from './routes/index';
import { Route as historyRoute } from './routes/history';
import { Route as analyticsRoute } from './routes/analytics';
import { Route as timelineRoute } from './routes/timeline';
import { Route as settingsRoute } from './routes/settings';

export const routeTree = rootRoute.addChildren([
  indexRoute,
  historyRoute,
  analyticsRoute,
  timelineRoute,
  settingsRoute,
]);
